{% set version = "1.2.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-webutils
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/webutils_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/webutils/webutils_{{ version }}.tar.gz
  sha256: 51243a1d7843dbb3968e7725c2266e1d68dcec43b919c320033f611ff9ca7f3c

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-curl >=2.5
    - r-jsonlite
  run:
    - r-base
    - r-curl >=2.5
    - r-jsonlite

test:
  commands:
    - $R -e "library('webutils')"           # [not win]
    - "\"%R%\" -e \"library('webutils')\""  # [win]

about:
  home: https://github.com/jeroen/webutils
  license: MIT
  summary: Parses http request data in application/json, multipart/form-data, or application/x-www-form-urlencoded format. Includes example of hosting and parsing html form data in R using either 'httpuv' or 'Rhttpd'.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: webutils
# Type: Package
# Title: Utility Functions for Developing Web Applications
# Version: 1.0
# Author: Jeroen Ooms
# Maintainer: Jeroen Ooms <jeroen@berkeley.edu>
# Description: Parses http request data in application/json, multipart/form-data, or application/x-www-form-urlencoded format. Includes example of hosting and parsing html form data in R using either 'httpuv' or 'Rhttpd'.
# License: MIT + file LICENSE
# URL: https://github.com/jeroen/webutils
# BugReports: https://github.com/jeroen/webutils/issues
# Imports: curl (>= 2.5), jsonlite
# Suggests: httpuv, testthat
# RoxygenNote: 6.1.1
# Language: en-US
# NeedsCompilation: yes
# Packaged: 2019-08-21 10:13:03 UTC; jeroen
# Repository: CRAN
# Date/Publication: 2019-08-21 12:40:06 UTC
