appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: Ie6bw8xSGAfzOJLlrTY4ZzQ4cA9JYzHveR2l1TmvXy6wSxY1h16piZ7GiJmEdAQd62efBxHbuCh5nXy4X+dw753gQT4MRpEwY+/U4vWhDsFHKx1ZaTtLuc5b2oe4AlfJUZx5Lm9eMxAYmfHTR0UQeUnUF4LMRPoj3He6EzNefNMlVE6fPzsmUXC8IjGaTJDUgO8WmNBuMNaecByUAgiNU/UcgopqdwXYwrnGq3ScT7iLrRAGInLjtHCoc00HAY8xBCoJX+sGuENWWbbwXpZfFSOsIoq0uP3HGCArgjbMCU9K21wtUSIQgzlIw4X4za/6j8KfHXsikA4JnrKylyFSX+P0OYet3Zjj1pvJydA5m8mFdZqEkoG7W7X6KbLPy5C6ie41jw7tvVTrwQTL5W3vG9Le5RsdEoxbwVQnaG+r0NMTN/+hGOeAY4hx06DhszDm0Woc0koy/gcCmC9K9lCohC7comZ8hiDWUCsAf7nBetH4m+T3BkZsPZyMenlDbqnUeuTe1ALPruw/3oU8do2BddWeAvlnXjRBQUMd+n6NNdVeQyGXZha408q/ZuWcAJ37vSpwRUzAncfaU3sCY71+OOr0yj7gtNdzOZe5KtWXUerdOEHrdvO8rPfPuppzFCrBq5zzH4GoHBsKZsYnN2+acPW8L+GVOAARb0wPd0v66U8=
conda_forge_output_validation: true
